apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoimg-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoimg
  template:
    metadata:
      labels:
        app: demoimg
    spec:
      containers:
      - name: demoimg
        image: demoimg:1.0
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10