apiVersion: v1
kind: Service
metadata:
  name: demoimg-service
spec:
  type: NodePort
  selector:
    app: demoimg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001